platform :ios, '7.0'

target 'KTLibs' do

pod 'RMUniversalAlert'
pod 'Masonry'
pod 'FMDB'
pod 'SVProgressHUD'
pod 'MWPhotoBrowser'
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~> 3.8'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'MJRefresh'
pod 'ZYCornerRadius', '~> 1.0.2'

end
